### PR TITLE
refactor(format): export format to be used

### PR DESCRIPTION
**Pull request by Tactless7**
I imported then exported the format function.
It allows the use of this method with the package.

### CODE REVIEW

**Comment by Tactless7** [comment]
Hi there @aymericbouzy , Is it possible for you to review my PR :)

**Review by aymericbouzy — APPROVED** [review]

**Comment by aymericbouzy** [comment]
Hi @Tactless7 thanks for contributing 🎉

**Comment by Tactless7** [comment]
Great ! Will it be released ?

**Comment by aymericbouzy** [comment]
Had to fix a few things, a lot was deprecated: published via [v4.0.0](https://github.com/aymericbouzy/french-ssn/releases/tag/v4.0.0)

**Pull request merged**
